theme: jekyll-theme-minimal
logo: https://user-images.githubusercontent.com/21345604/151689876-405ac631-5dc6-46c1-8d19-368cf4e36335.png
title: ClipsAndPatterns
email: clipsandpatterns@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Decades-long music project of <a href="https://grechin.org">Sergey Grechin</a>. Contacts: bsv_2k@mail.ru, clipsandpatterns@gmail.com
url: https://clipsandpatterns.com
# Build settings
plugins:
  - jekyll-feed